--[[
	PropSetup (generated by slimes/tools/build_props.py; edit that, not this file)

	1. Import the prop .glb files with File > Import 3D. Keep the model names (ValleyGate, Tree_A, ...).
	2. Select the imported props (or select nothing to scan Workspace, ReplicatedStorage and
	   ServerStorage), paste this whole file into the Command Bar and press Enter.

	For each prop it:
	  - colours every part, sets its material and transparency, and turns collisions on only for the
	    solid parts (trunks, rocks, pillars), so players don't snag on petals and reeds
	  - anchors every part and moves them straight under the model
	  - puts the pivot at the bottom centre and scales the prop to its height in studs
	  - adds sign text (the gate's "SLIME VALLEY", each zone arch's name and rarity line, the statue's
	    plaque) and lights for glowing parts
	  - tags it with PropZone and PropKind attributes, which ZoneDresser.lua and CliffDresser.lua use
	    to find the right pieces for a zone

	Running it again is safe.
]]

local SPECS = {
--@SPECS@
}

local function partKey(parts, name)
	if parts[name] then
		return name
	end
	for key in pairs(parts) do
		if name:sub(1, #key) == key and not name:sub(#key + 1, #key + 1):match("%w") then
			return key
		end
	end
	return nil
end

local function isProp(model, spec)
	local any = false
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("BasePart") then
			if not partKey(spec.Parts, d.Name) then
				return false
			end
			any = true
		end
	end
	return any
end

local function addSign(part, sign)
	for _, c in ipairs(part:GetChildren()) do
		if c:IsA("SurfaceGui") and c.Name:match("^SignGui") then
			c:Destroy()
		end
	end
	local faces = sign.FrontOnly and { Enum.NormalId.Front } or { Enum.NormalId.Front, Enum.NormalId.Back }
	for _, face in ipairs(faces) do
		local gui = Instance.new("SurfaceGui")
		gui.Name = "SignGui" .. face.Name
		gui.Face = face
		gui.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
		gui.PixelsPerStud = sign.PixelsPerStud
		gui.LightInfluence = 0
		local hasSub = sign.Sub ~= ""
		local function addLabel(name, text, color, y, height)
			local label = Instance.new("TextLabel")
			label.Name = name
			label.BackgroundTransparency = 1
			label.AnchorPoint = Vector2.new(0.5, 0.5)
			label.Position = UDim2.fromScale(0.5, y)
			label.Size = UDim2.fromScale(0.92, height)
			label.Font = Enum.Font.FredokaOne
			label.TextScaled = true
			label.Text = text
			label.TextColor3 = color
			local stroke = Instance.new("UIStroke")
			stroke.Color = Color3.new(0, 0, 0)
			stroke.Transparency = 0.4
			stroke.Thickness = 3
			stroke.Parent = label
			label.Parent = gui
		end
		if hasSub then
			addLabel("Label", sign.Text, sign.Color, 0.38, 0.52)
			addLabel("SubLabel", sign.Sub, Color3.new(1, 1, 1), 0.8, 0.26)
		else
			addLabel("Label", sign.Text, sign.Color, 0.5, 0.8)
		end
		gui.Parent = part
	end
end

local function setup(model, spec)
	local parts = {}
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("BasePart") then
			table.insert(parts, d)
		end
	end
	for _, p in ipairs(parts) do
		p.Parent = model
	end
	for _, c in ipairs(model:GetChildren()) do
		if (c:IsA("Model") or c:IsA("Folder")) and #c:GetDescendants() == 0 then
			c:Destroy()
		end
	end

	local main
	for _, p in ipairs(parts) do
		local key = partKey(spec.Parts, p.Name)
		local look = spec.Parts[key]
		p.Name = key
		p.Color, p.Material, p.Transparency = look[1], look[2], look[3]
		p.Anchored = true
		p.CanCollide = look[4]
		p.CanTouch = look[4]
		p.CanQuery = look[4]
		p.CastShadow = look[2] ~= Enum.Material.Neon and look[3] < 0.3
		for _, c in ipairs(p:GetChildren()) do
			if c:IsA("SurfaceAppearance") or (c:IsA("PointLight") and c.Name == "PropLight") then
				c:Destroy()
			end
		end
		if key == spec.Main and not main then
			main = p
		end
	end
	model.PrimaryPart = main

	local cf, size = model:GetBoundingBox()
	local bottom = cf.Position - Vector3.new(0, size.Y / 2, 0)
	model.WorldPivot = CFrame.new(bottom)
	if size.Y > 0 then
		local factor = spec.Height / size.Y
		if math.abs(factor - 1) > 1e-3 then
			model:ScaleTo(model:GetScale() * factor)
		end
	end

	for _, sign in ipairs(spec.Signs) do
		for _, p in ipairs(parts) do
			if p.Name == sign.Part then
				addSign(p, sign)
			end
		end
	end
	for _, name in ipairs(spec.Lights) do
		for _, p in ipairs(parts) do
			if p.Name == name then
				local light = Instance.new("PointLight")
				light.Name = "PropLight"
				light.Color = p.Color
				light.Range = 16
				light.Brightness = 1.5
				light.Parent = p
			end
		end
	end
	model:SetAttribute("PropZone", spec.Zone)
	model:SetAttribute("PropKind", spec.Kind)
end

local candidates = {}
local okSel, selection = pcall(function()
	return game:GetService("Selection"):Get()
end)
if okSel and #selection > 0 then
	for _, s in ipairs(selection) do
		table.insert(candidates, s)
		for _, d in ipairs(s:GetDescendants()) do
			table.insert(candidates, d)
		end
	end
else
	for _, service in ipairs({ workspace, game:GetService("ReplicatedStorage"), game:GetService("ServerStorage") }) do
		for _, d in ipairs(service:GetDescendants()) do
			table.insert(candidates, d)
		end
	end
end

local done = {}
for _, m in ipairs(candidates) do
	local spec = m:IsA("Model") and SPECS[m.Name]
	if spec and m.Parent and isProp(m, spec) then
		setup(m, spec)
		table.insert(done, m.Name)
	end
end
print(("PropSetup: set up %d prop(s): %s"):format(#done, table.concat(done, ", ")))
