--[[
	SlimeSetup (generated by slimes/tools/build_slimes.py; edit that, not this file)

	1. Import the .glb files with File > Import 3D. Keep the model names (LilGreen, BlueBlob, ...).
	2. Select the imported slimes (or select nothing to scan Workspace, ReplicatedStorage and
	   ServerStorage), paste this whole file into the Command Bar and press Enter.

	For each slime model it:
	  - colours every part and sets its material and transparency
	  - moves the parts straight under the model and welds them to Body (the PrimaryPart)
	  - puts the pivot at the bottom centre, turned so the pivot's LookVector is the way the face looks
	  - scales the model to its size in studs
	  - adds Rarity and Size attributes

	Running it again is safe. A model is only touched when every part in it is a known slime part,
	so other models that happen to be called King or Ghost are left alone.
]]

local SPECS = {
--@SPECS@
}

local function partKey(parts, name)
	if parts[name] then
		return name
	end
	-- the importer can add a suffix such as "Body_1"
	for key in pairs(parts) do
		if name:sub(1, #key) == key and not name:sub(#key + 1, #key + 1):match("%w") then
			return key
		end
	end
	return nil
end

local function worldBounds(part)
	local cf, half = part.CFrame, part.Size / 2
	local lo = Vector3.new(math.huge, math.huge, math.huge)
	local hi = -lo
	for _, x in ipairs({ -1, 1 }) do
		for _, y in ipairs({ -1, 1 }) do
			for _, z in ipairs({ -1, 1 }) do
				local p = cf:PointToWorldSpace(Vector3.new(x * half.X, y * half.Y, z * half.Z))
				lo = lo:Min(p)
				hi = hi:Max(p)
			end
		end
	end
	return lo, hi
end

local function isSlime(model, spec)
	local hasBody = false
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("BasePart") then
			local key = partKey(spec.Parts, d.Name)
			if not key then
				return false
			end
			hasBody = hasBody or key == "Body"
		end
	end
	return hasBody
end

local function setup(model, spec)
	local parts = {}
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("BasePart") then
			table.insert(parts, d)
		end
	end

	-- flatten whatever nesting the importer made
	for _, p in ipairs(parts) do
		p.Parent = model
	end
	for _, c in ipairs(model:GetChildren()) do
		if (c:IsA("Model") or c:IsA("Folder")) and #c:GetDescendants() == 0 then
			c:Destroy()
		end
	end

	local body
	local facePos, faceCount = Vector3.zero, 0
	for _, p in ipairs(parts) do
		local key = partKey(spec.Parts, p.Name)
		local look = spec.Parts[key]
		p.Name = key
		p.Color, p.Material, p.Transparency = look[1], look[2], look[3]
		for _, c in ipairs(p:GetChildren()) do
			if c:IsA("SurfaceAppearance") or (c:IsA("WeldConstraint") and c.Name == "SlimeWeld") then
				c:Destroy()
			end
		end
		if key == "Body" and not body then
			body = p
		end
		if key == spec.Face then
			facePos += p.Position
			faceCount += 1
		end
	end

	model.PrimaryPart = body
	for _, p in ipairs(parts) do
		if p == body then
			p.Anchored = true
		else
			p.Anchored = false
			p.CanCollide = false
			p.CanTouch = false
			p.CanQuery = false
			p.Massless = true
			local weld = Instance.new("WeldConstraint")
			weld.Name = "SlimeWeld"
			weld.Part0 = body
			weld.Part1 = p
			weld.Parent = p
		end
	end

	-- pivot at the bottom centre of the body, looking the way the face looks
	local lo, hi = worldBounds(body)
	local centre = (lo + hi) / 2
	local bottom = Vector3.new(centre.X, lo.Y, centre.Z)
	local look = Vector3.new(0, 0, -1)
	if faceCount > 0 then
		local f = facePos / faceCount - centre
		if Vector3.new(f.X, 0, f.Z).Magnitude > 1e-3 then
			look = Vector3.new(f.X, 0, f.Z).Unit
		end
	end
	model.WorldPivot = CFrame.lookAt(bottom, bottom + look)
	model:PivotTo(CFrame.new(bottom))

	-- exact size: the body is BodyWidth studs across
	local lo2, hi2 = worldBounds(body)
	local width = hi2.X - lo2.X
	if width > 0 then
		local factor = spec.BodyWidth / width
		if math.abs(factor - 1) > 1e-3 then
			model:ScaleTo(model:GetScale() * factor)
		end
	end

	model:SetAttribute("Rarity", spec.Rarity)
	model:SetAttribute("Size", spec.Size)
	return true
end

local candidates = {}
local okSel, selection = pcall(function()
	return game:GetService("Selection"):Get()
end)
if okSel and #selection > 0 then
	for _, s in ipairs(selection) do
		table.insert(candidates, s)
		for _, d in ipairs(s:GetDescendants()) do
			table.insert(candidates, d)
		end
	end
else
	for _, service in ipairs({ workspace, game:GetService("ReplicatedStorage"), game:GetService("ServerStorage") }) do
		for _, d in ipairs(service:GetDescendants()) do
			table.insert(candidates, d)
		end
	end
end

local done = {}
for _, m in ipairs(candidates) do
	local spec = m:IsA("Model") and SPECS[m.Name]
	if spec and m.Parent and isSlime(m, spec) then
		setup(m, spec)
		table.insert(done, m.Name)
	end
end
print(("SlimeSetup: set up %d slime(s): %s"):format(#done, table.concat(done, ", ")))
