--[[
	BaseBuilder (generated by slimes/tools/build_base.py; edit that, not this file)

	Paste this whole file into the Studio Command Bar and press Enter. It builds a model called
	"SlimeBase" at PLACE_AT below. The pivot is the bottom centre of the base and the entrance faces
	the pivot's LookVector, so you can move or clone it with base:PivotTo(cframe).

	What your game scripts can use:
	  Slots/Slot1 .. Slot10      Model per pet slot (1-5 front row, 6-10 back row)
	      Top.PetSpot            Attachment where the pet stands (its WorldCFrame faces the street)
	      Rim                    neon ring; recolour it to the pet's rarity
	      Plaque.PlaqueGui.Label TextLabel for the earnings text
	  Entrance/Sign.SignGui      Avatar (ImageLabel) and OwnerName (TextLabel)
	  Door/Field, Door/Beam      the laser door; see setDoorLocked below for how to lock/unlock it
	  Door/Field.LockTimer.Label BillboardGui text such as "LOCKED 0:30"
	  LockButton/Button          step on it to lock the base
]]

local PLACE_AT = CFrame.new(0, 0, 0)
local OWNER_TEXT = nil -- nil: uses your Studio account, e.g. "Ultrevo's Base"

local PARTS = {
	{"Floor", "Plinth", "Block", {52, 1, 40}, {0, 0.5, 0}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-24, 1.1, -18}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-24, 1.1, -14}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-24, 1.1, -10}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-24, 1.1, -6}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-24, 1.1, -2}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-20, 1.1, -18}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-20, 1.1, -14}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-20, 1.1, -10}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-20, 1.1, -6}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-20, 1.1, -2}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-16, 1.1, -18}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-16, 1.1, -14}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-16, 1.1, -10}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-16, 1.1, -6}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-16, 1.1, -2}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-12, 1.1, -18}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-12, 1.1, -14}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-12, 1.1, -10}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-12, 1.1, -6}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-12, 1.1, -2}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-8, 1.1, -18}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-8, 1.1, -14}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-8, 1.1, -10}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-8, 1.1, -6}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-8, 1.1, -2}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-4, 1.1, -18}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-4, 1.1, -14}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-4, 1.1, -10}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-4, 1.1, -6}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {-4, 1.1, -2}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {0, 1.1, -18}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {0, 1.1, -14}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {0, 1.1, -10}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {0, 1.1, -6}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {0, 1.1, -2}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {4, 1.1, -18}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {4, 1.1, -14}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {4, 1.1, -10}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {4, 1.1, -6}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {4, 1.1, -2}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {8, 1.1, -18}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {8, 1.1, -14}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {8, 1.1, -10}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {8, 1.1, -6}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {8, 1.1, -2}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {12, 1.1, -18}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {12, 1.1, -14}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {12, 1.1, -10}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {12, 1.1, -6}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {12, 1.1, -2}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {16, 1.1, -18}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {16, 1.1, -14}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {16, 1.1, -10}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {16, 1.1, -6}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {16, 1.1, -2}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {20, 1.1, -18}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {20, 1.1, -14}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {20, 1.1, -10}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {20, 1.1, -6}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {20, 1.1, -2}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {24, 1.1, -18}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {24, 1.1, -14}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {24, 1.1, -10}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {24, 1.1, -6}, false, "#FFE0EA", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "Tile", "Block", {4, 0.2, 4}, {24, 1.1, -2}, false, "#FFF1F5", "SmoothPlastic", 0, true},
	{"Floor", "Tier", "Block", {52, 1, 20}, {0, 1.5, 10}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-24, 2.1, 2}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-24, 2.1, 6}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-24, 2.1, 10}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-24, 2.1, 14}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-24, 2.1, 18}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-20, 2.1, 2}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-20, 2.1, 6}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-20, 2.1, 10}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-20, 2.1, 14}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-20, 2.1, 18}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-16, 2.1, 2}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-16, 2.1, 6}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-16, 2.1, 10}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-16, 2.1, 14}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-16, 2.1, 18}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-12, 2.1, 2}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-12, 2.1, 6}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-12, 2.1, 10}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-12, 2.1, 14}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-12, 2.1, 18}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-8, 2.1, 2}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-8, 2.1, 6}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-8, 2.1, 10}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-8, 2.1, 14}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-8, 2.1, 18}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-4, 2.1, 2}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-4, 2.1, 6}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-4, 2.1, 10}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-4, 2.1, 14}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {-4, 2.1, 18}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {0, 2.1, 2}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {0, 2.1, 6}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {0, 2.1, 10}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {0, 2.1, 14}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {0, 2.1, 18}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {4, 2.1, 2}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {4, 2.1, 6}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {4, 2.1, 10}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {4, 2.1, 14}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {4, 2.1, 18}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {8, 2.1, 2}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {8, 2.1, 6}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {8, 2.1, 10}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {8, 2.1, 14}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {8, 2.1, 18}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {12, 2.1, 2}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {12, 2.1, 6}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {12, 2.1, 10}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {12, 2.1, 14}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {12, 2.1, 18}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {16, 2.1, 2}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {16, 2.1, 6}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {16, 2.1, 10}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {16, 2.1, 14}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {16, 2.1, 18}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {20, 2.1, 2}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {20, 2.1, 6}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {20, 2.1, 10}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {20, 2.1, 14}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {20, 2.1, 18}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {24, 2.1, 2}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {24, 2.1, 6}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {24, 2.1, 10}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {24, 2.1, 14}, false, "#E3DAFF", "SmoothPlastic", 0, true},
	{"Floor/Tiles", "TierTile", "Block", {4, 0.2, 4}, {24, 2.1, 18}, false, "#F1ECFF", "SmoothPlastic", 0, true},
	{"Floor", "TierEdge", "Block", {50, 0.3, 0.3}, {0, 1.8, -0.12}, false, "#6CFFC9", "Neon", 0, true},
	{"Floor", "StepUpper", "Block", {16, 0.8, 1}, {0, 0.4, -20.5}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Floor", "StepLower", "Block", {16, 0.4, 1}, {0, 0.2, -21.5}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Walls", "SideWall", "Block", {1, 1.8, 40}, {-25.5, 1.9, 0}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "SideGlass", "Block", {0.4, 6.2, 38}, {-25.5, 5.9, 0}, false, "#CDEBFF", "Glass", 0.6, true},
	{"Walls", "SideRail", "Block", {1.2, 1, 40}, {-25.5, 9.5, 0}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "Post", "Block", {1.3, 6.2, 1.3}, {-25.5, 5.9, -6.667}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "Post", "Block", {1.3, 6.2, 1.3}, {-25.5, 5.9, 6.667}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "FrontWall", "Block", {16, 1.8, 1}, {-18, 1.9, -19.5}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "FrontGlass", "Block", {14, 6.2, 0.4}, {-18, 5.9, -19.5}, false, "#CDEBFF", "Glass", 0.6, true},
	{"Walls", "FrontRail", "Block", {16, 1, 1.2}, {-18, 9.5, -19.5}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "Post", "Block", {1.3, 6.2, 1.3}, {-17.5, 5.9, -19.5}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "SideWall", "Block", {1, 1.8, 40}, {25.5, 1.9, 0}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "SideGlass", "Block", {0.4, 6.2, 38}, {25.5, 5.9, 0}, false, "#CDEBFF", "Glass", 0.6, true},
	{"Walls", "SideRail", "Block", {1.2, 1, 40}, {25.5, 9.5, 0}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "Post", "Block", {1.3, 6.2, 1.3}, {25.5, 5.9, -6.667}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "Post", "Block", {1.3, 6.2, 1.3}, {25.5, 5.9, 6.667}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "FrontWall", "Block", {16, 1.8, 1}, {18, 1.9, -19.5}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "FrontGlass", "Block", {14, 6.2, 0.4}, {18, 5.9, -19.5}, false, "#CDEBFF", "Glass", 0.6, true},
	{"Walls", "FrontRail", "Block", {16, 1, 1.2}, {18, 9.5, -19.5}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "Post", "Block", {1.3, 6.2, 1.3}, {17.5, 5.9, -19.5}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "BackWall", "Block", {52, 7.8, 1}, {0, 6.1, 19.5}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Walls", "BackRail", "Block", {52, 1, 1.2}, {0, 10.5, 19.5}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Walls", "BackStripe", "Block", {48, 0.4, 0.2}, {0, 7.5, 18.95}, false, "#6CFFC9", "Neon", 0, true},
	{"Pillars", "Pillar", "Cylinder", {10.6, 3, 3}, {-25.5, 5.3, -19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Pillars", "Band", "Cylinder", {0.6, 3.3, 3.3}, {-25.5, 2.8, -19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Pillars", "Band", "Cylinder", {0.6, 3.3, 3.3}, {-25.5, 9.4, -19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Pillars", "Lamp", "Ball", {2.8, 2.8, 2.8}, {-25.5, 11.9, -19.5}, false, "#6CFFC9", "Neon", 0, false},
	{"Pillars", "Pillar", "Cylinder", {10.6, 3, 3}, {-25.5, 5.3, 19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Pillars", "Band", "Cylinder", {0.6, 3.3, 3.3}, {-25.5, 2.8, 19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Pillars", "Band", "Cylinder", {0.6, 3.3, 3.3}, {-25.5, 9.4, 19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Pillars", "Lamp", "Ball", {2.8, 2.8, 2.8}, {-25.5, 11.9, 19.5}, false, "#6CFFC9", "Neon", 0, false},
	{"Pillars", "Pillar", "Cylinder", {10.6, 3, 3}, {25.5, 5.3, -19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Pillars", "Band", "Cylinder", {0.6, 3.3, 3.3}, {25.5, 2.8, -19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Pillars", "Band", "Cylinder", {0.6, 3.3, 3.3}, {25.5, 9.4, -19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Pillars", "Lamp", "Ball", {2.8, 2.8, 2.8}, {25.5, 11.9, -19.5}, false, "#6CFFC9", "Neon", 0, false},
	{"Pillars", "Pillar", "Cylinder", {10.6, 3, 3}, {25.5, 5.3, 19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Pillars", "Band", "Cylinder", {0.6, 3.3, 3.3}, {25.5, 2.8, 19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Pillars", "Band", "Cylinder", {0.6, 3.3, 3.3}, {25.5, 9.4, 19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Pillars", "Lamp", "Ball", {2.8, 2.8, 2.8}, {25.5, 11.9, 19.5}, false, "#6CFFC9", "Neon", 0, false},
	{"Entrance", "ArchPillar", "Cylinder", {18.4, 3, 3}, {-8.5, 9.2, -19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Entrance", "Band", "Cylinder", {0.6, 3.3, 3.3}, {-8.5, 2.8, -19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Entrance", "Band", "Cylinder", {0.6, 3.3, 3.3}, {-8.5, 9.4, -19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Entrance", "Lamp", "Ball", {2.6, 2.6, 2.6}, {-8.5, 19.6, -19.5}, false, "#6CFFC9", "Neon", 0, false},
	{"Entrance", "ArchPillar", "Cylinder", {18.4, 3, 3}, {8.5, 9.2, -19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Entrance", "Band", "Cylinder", {0.6, 3.3, 3.3}, {8.5, 2.8, -19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Entrance", "Band", "Cylinder", {0.6, 3.3, 3.3}, {8.5, 9.4, -19.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Entrance", "Lamp", "Ball", {2.6, 2.6, 2.6}, {8.5, 19.6, -19.5}, false, "#6CFFC9", "Neon", 0, false},
	{"Entrance", "DoorBeam", "Block", {17, 1, 1.2}, {0, 9.5, -19.5}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Entrance", "Sign", "Block", {27, 4.8, 0.8}, {0, 14.8, -20.9}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Entrance", "SignFrame", "Block", {28.2, 0.6, 0.9}, {0, 17.5, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Entrance", "SignFrame", "Block", {28.2, 0.6, 0.9}, {0, 12.1, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Entrance", "SignFrame", "Block", {0.6, 6, 0.9}, {-13.8, 14.8, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Entrance", "SignFrame", "Block", {0.6, 6, 0.9}, {13.8, 14.8, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, true},
	{"Entrance/Drips", "Drip", "Cylinder", {0.9, 0.84, 0.84}, {-12.6, 11.5, -21.15}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {1.2, 1.2, 1.2}, {-12.6, 11.05, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {0.9, 0.9, 0.9}, {-10.9, 11.95, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drip", "Cylinder", {1.5, 0.98, 0.98}, {-9.4, 11.2, -21.15}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {1.4, 1.4, 1.4}, {-9.4, 10.45, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drip", "Cylinder", {0.3, 0.7, 0.7}, {-7.6, 11.8, -21.15}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {1, 1, 1}, {-7.6, 11.65, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {1.2, 1.2, 1.2}, {-6, 11.95, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drip", "Cylinder", {1.1, 1.05, 1.05}, {-4.3, 11.4, -21.15}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {1.5, 1.5, 1.5}, {-4.3, 10.85, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {0.9, 0.9, 0.9}, {-2.5, 11.95, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drip", "Cylinder", {1.7, 0.91, 0.91}, {-0.9, 11.1, -21.15}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {1.3, 1.3, 1.3}, {-0.9, 10.25, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drip", "Cylinder", {0.4, 0.7, 0.7}, {0.8, 11.75, -21.15}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {1, 1, 1}, {0.8, 11.55, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {1.4, 1.4, 1.4}, {2.4, 11.95, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drip", "Cylinder", {1.2, 0.77, 0.77}, {4.1, 11.35, -21.15}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {1.1, 1.1, 1.1}, {4.1, 10.75, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {0.9, 0.9, 0.9}, {5.8, 11.95, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drip", "Cylinder", {0.6, 1.05, 1.05}, {7.4, 11.65, -21.15}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {1.5, 1.5, 1.5}, {7.4, 11.35, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {1.1, 1.1, 1.1}, {9.1, 11.95, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drip", "Cylinder", {1.3, 0.98, 0.98}, {10.8, 11.3, -21.15}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {1.4, 1.4, 1.4}, {10.8, 10.65, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drip", "Cylinder", {0.3, 0.7, 0.7}, {12.6, 11.8, -21.15}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance/Drips", "Drop", "Ball", {1, 1, 1}, {12.6, 11.65, -21.15}, false, "#FF5C7A", "SmoothPlastic", 0, false},
	{"Entrance", "Mascot", "Ball", {3.4, 3.4, 3.4}, {-11, 19.1, -20.9}, false, "#6CFFC9", "SmoothPlastic", 0, false},
	{"Entrance", "MascotBase", "Block", {3.2, 0.6, 2.2}, {-11, 17.8, -20.9}, false, "#6CFFC9", "SmoothPlastic", 0, false},
	{"Entrance", "MascotEye", "Ball", {0.55, 0.55, 0.55}, {-11.55, 19.5, -22.4}, false, "#1E2440", "SmoothPlastic", 0, false},
	{"Entrance", "MascotEye", "Ball", {0.55, 0.55, 0.55}, {-10.45, 19.5, -22.4}, false, "#1E2440", "SmoothPlastic", 0, false},
	{"Door", "Field", "Block", {14, 8, 0.3}, {0, 5, -19.5}, false, "#FF3355", "ForceField", 0, true},
	{"Door", "Beam", "Cylinder", {14, 0.35, 0.35}, {0, 2.6, -19.5}, false, "#FF3355", "Neon", 0, false},
	{"Door", "Beam", "Cylinder", {14, 0.35, 0.35}, {0, 4.4, -19.5}, false, "#FF3355", "Neon", 0, false},
	{"Door", "Beam", "Cylinder", {14, 0.35, 0.35}, {0, 6.2, -19.5}, false, "#FF3355", "Neon", 0, false},
	{"Door", "Beam", "Cylinder", {14, 0.35, 0.35}, {0, 8, -19.5}, false, "#FF3355", "Neon", 0, false},
	{"LockButton", "Pedestal", "Cylinder", {1, 3.4, 3.4}, {13, 1.7, -16.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"LockButton", "Button", "Cylinder", {0.5, 2.6, 2.6}, {13, 2.45, -16.5}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FF3355", "Neon", 0, true},
	{"Slots/Slot1", "Rim", "Cylinder", {0.25, 8.4, 8.4}, {-20, 1.325, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#6CFFC9", "Neon", 0, true},
	{"Slots/Slot1", "Base", "Cylinder", {0.7, 8, 8}, {-20, 1.55, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot1", "Top", "Cylinder", {0.25, 7, 7}, {-20, 2.025, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FFFFFF", "SmoothPlastic", 0, true},
	{"Slots/Slot1", "PlaqueStand", "Block", {0.6, 0.8, 0.6}, {-20, 1.6, -13}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot1", "Plaque", "Block", {4.6, 1.6, 0.3}, {-20, 2.5, -13}, {1, 0, 0, 0, 0.906308, -0.422618, 0, 0.422618, 0.906308}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot2", "Rim", "Cylinder", {0.25, 8.4, 8.4}, {-10, 1.325, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#6CFFC9", "Neon", 0, true},
	{"Slots/Slot2", "Base", "Cylinder", {0.7, 8, 8}, {-10, 1.55, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot2", "Top", "Cylinder", {0.25, 7, 7}, {-10, 2.025, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FFFFFF", "SmoothPlastic", 0, true},
	{"Slots/Slot2", "PlaqueStand", "Block", {0.6, 0.8, 0.6}, {-10, 1.6, -13}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot2", "Plaque", "Block", {4.6, 1.6, 0.3}, {-10, 2.5, -13}, {1, 0, 0, 0, 0.906308, -0.422618, 0, 0.422618, 0.906308}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot3", "Rim", "Cylinder", {0.25, 8.4, 8.4}, {0, 1.325, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#6CFFC9", "Neon", 0, true},
	{"Slots/Slot3", "Base", "Cylinder", {0.7, 8, 8}, {0, 1.55, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot3", "Top", "Cylinder", {0.25, 7, 7}, {0, 2.025, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FFFFFF", "SmoothPlastic", 0, true},
	{"Slots/Slot3", "PlaqueStand", "Block", {0.6, 0.8, 0.6}, {0, 1.6, -13}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot3", "Plaque", "Block", {4.6, 1.6, 0.3}, {0, 2.5, -13}, {1, 0, 0, 0, 0.906308, -0.422618, 0, 0.422618, 0.906308}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot4", "Rim", "Cylinder", {0.25, 8.4, 8.4}, {10, 1.325, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#6CFFC9", "Neon", 0, true},
	{"Slots/Slot4", "Base", "Cylinder", {0.7, 8, 8}, {10, 1.55, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot4", "Top", "Cylinder", {0.25, 7, 7}, {10, 2.025, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FFFFFF", "SmoothPlastic", 0, true},
	{"Slots/Slot4", "PlaqueStand", "Block", {0.6, 0.8, 0.6}, {10, 1.6, -13}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot4", "Plaque", "Block", {4.6, 1.6, 0.3}, {10, 2.5, -13}, {1, 0, 0, 0, 0.906308, -0.422618, 0, 0.422618, 0.906308}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot5", "Rim", "Cylinder", {0.25, 8.4, 8.4}, {20, 1.325, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#6CFFC9", "Neon", 0, true},
	{"Slots/Slot5", "Base", "Cylinder", {0.7, 8, 8}, {20, 1.55, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot5", "Top", "Cylinder", {0.25, 7, 7}, {20, 2.025, -8}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FFFFFF", "SmoothPlastic", 0, true},
	{"Slots/Slot5", "PlaqueStand", "Block", {0.6, 0.8, 0.6}, {20, 1.6, -13}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot5", "Plaque", "Block", {4.6, 1.6, 0.3}, {20, 2.5, -13}, {1, 0, 0, 0, 0.906308, -0.422618, 0, 0.422618, 0.906308}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot6", "Rim", "Cylinder", {0.25, 8.4, 8.4}, {-20, 2.325, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#6CFFC9", "Neon", 0, true},
	{"Slots/Slot6", "Base", "Cylinder", {0.7, 8, 8}, {-20, 2.55, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot6", "Top", "Cylinder", {0.25, 7, 7}, {-20, 3.025, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FFFFFF", "SmoothPlastic", 0, true},
	{"Slots/Slot6", "PlaqueStand", "Block", {0.6, 0.8, 0.6}, {-20, 2.6, 4}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot6", "Plaque", "Block", {4.6, 1.6, 0.3}, {-20, 3.5, 4}, {1, 0, 0, 0, 0.906308, -0.422618, 0, 0.422618, 0.906308}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot7", "Rim", "Cylinder", {0.25, 8.4, 8.4}, {-10, 2.325, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#6CFFC9", "Neon", 0, true},
	{"Slots/Slot7", "Base", "Cylinder", {0.7, 8, 8}, {-10, 2.55, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot7", "Top", "Cylinder", {0.25, 7, 7}, {-10, 3.025, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FFFFFF", "SmoothPlastic", 0, true},
	{"Slots/Slot7", "PlaqueStand", "Block", {0.6, 0.8, 0.6}, {-10, 2.6, 4}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot7", "Plaque", "Block", {4.6, 1.6, 0.3}, {-10, 3.5, 4}, {1, 0, 0, 0, 0.906308, -0.422618, 0, 0.422618, 0.906308}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot8", "Rim", "Cylinder", {0.25, 8.4, 8.4}, {0, 2.325, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#6CFFC9", "Neon", 0, true},
	{"Slots/Slot8", "Base", "Cylinder", {0.7, 8, 8}, {0, 2.55, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot8", "Top", "Cylinder", {0.25, 7, 7}, {0, 3.025, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FFFFFF", "SmoothPlastic", 0, true},
	{"Slots/Slot8", "PlaqueStand", "Block", {0.6, 0.8, 0.6}, {0, 2.6, 4}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot8", "Plaque", "Block", {4.6, 1.6, 0.3}, {0, 3.5, 4}, {1, 0, 0, 0, 0.906308, -0.422618, 0, 0.422618, 0.906308}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot9", "Rim", "Cylinder", {0.25, 8.4, 8.4}, {10, 2.325, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#6CFFC9", "Neon", 0, true},
	{"Slots/Slot9", "Base", "Cylinder", {0.7, 8, 8}, {10, 2.55, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot9", "Top", "Cylinder", {0.25, 7, 7}, {10, 3.025, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FFFFFF", "SmoothPlastic", 0, true},
	{"Slots/Slot9", "PlaqueStand", "Block", {0.6, 0.8, 0.6}, {10, 2.6, 4}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot9", "Plaque", "Block", {4.6, 1.6, 0.3}, {10, 3.5, 4}, {1, 0, 0, 0, 0.906308, -0.422618, 0, 0.422618, 0.906308}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot10", "Rim", "Cylinder", {0.25, 8.4, 8.4}, {20, 2.325, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#6CFFC9", "Neon", 0, true},
	{"Slots/Slot10", "Base", "Cylinder", {0.7, 8, 8}, {20, 2.55, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot10", "Top", "Cylinder", {0.25, 7, 7}, {20, 3.025, 9}, {0, -1, 0, 1, 0, 0, 0, 0, 1}, "#FFFFFF", "SmoothPlastic", 0, true},
	{"Slots/Slot10", "PlaqueStand", "Block", {0.6, 0.8, 0.6}, {20, 2.6, 4}, false, "#1E2440", "SmoothPlastic", 0, true},
	{"Slots/Slot10", "Plaque", "Block", {4.6, 1.6, 0.3}, {20, 3.5, 4}, {1, 0, 0, 0, 0.906308, -0.422618, 0, 0.422618, 0.906308}, "#1E2440", "SmoothPlastic", 0, true},
}

local model = Instance.new("Model")
model.Name = "SlimeBase"

local function container(path)
	local parent = model
	if path == "" then
		return parent
	end
	for name in path:gmatch("[^/]+") do
		local child = parent:FindFirstChild(name)
		if not child then
			child = Instance.new("Model")
			child.Name = name
			child.Parent = parent
		end
		parent = child
	end
	return parent
end

for _, p in ipairs(PARTS) do
	local path, name, shape, size, pos, rot, color, material, transparency, collide = table.unpack(p, 1, 10)
	local part = Instance.new("Part")
	part.Name = name
	part.Shape = Enum.PartType[shape]
	part.Size = Vector3.new(size[1], size[2], size[3])
	if rot then
		part.CFrame = CFrame.new(pos[1], pos[2], pos[3], rot[1], rot[2], rot[3], rot[4], rot[5], rot[6], rot[7], rot[8], rot[9])
	else
		part.CFrame = CFrame.new(pos[1], pos[2], pos[3])
	end
	part.Color = Color3.fromHex(color)
	part.Material = Enum.Material[material]
	part.Transparency = transparency
	part.CanCollide = collide
	part.CanTouch = collide or name == "Button"
	part.Anchored = true
	part.TopSurface = Enum.SurfaceType.Smooth
	part.BottomSurface = Enum.SurfaceType.Smooth
	part.CastShadow = material ~= "Neon" and material ~= "Glass"
	part.Parent = container(path)
end

local function find(path)
	local node = model
	for name in path:gmatch("[^/]+") do
		node = node:FindFirstChild(name)
	end
	return node
end

local FONT = Enum.Font.FredokaOne

local function label(parent, text, color, strokeColor)
	local l = Instance.new("TextLabel")
	l.Name = "Label"
	l.BackgroundTransparency = 1
	l.Size = UDim2.fromScale(1, 1)
	l.Font = FONT
	l.TextScaled = true
	l.Text = text
	l.TextColor3 = color
	local stroke = Instance.new("UIStroke")
	stroke.Color = strokeColor
	stroke.Thickness = 3
	stroke.Parent = l
	l.Parent = parent
	return l
end

-- sign: round avatar on the left, owner name on the right
local sign = find("Entrance/Sign")
local gui = Instance.new("SurfaceGui")
gui.Name = "SignGui"
gui.Face = Enum.NormalId.Front
gui.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
gui.PixelsPerStud = 40
gui.LightInfluence = 0
gui.Parent = sign
local avatar = Instance.new("ImageLabel")
avatar.Name = "Avatar"
avatar.AnchorPoint = Vector2.new(0, 0.5)
avatar.Position = UDim2.new(0, 40, 0.5, 0)
avatar.Size = UDim2.fromOffset(150, 150)
avatar.BackgroundColor3 = Color3.fromHex("#2C3560")
avatar.Parent = gui
Instance.new("UICorner", avatar).CornerRadius = UDim.new(0.5, 0)
local ring = Instance.new("UIStroke")
ring.Color = Color3.fromHex("#FF5C7A")
ring.Thickness = 8
ring.Parent = avatar
local nameLabel = label(gui, "", Color3.fromHex("#FFB3C2"), Color3.fromHex("#0E1226"))
nameLabel.Name = "OwnerName"
nameLabel.AnchorPoint = Vector2.new(1, 0.5)
nameLabel.Position = UDim2.new(1, -40, 0.5, 0)
nameLabel.Size = UDim2.new(1, -250, 0.62, 0)

local ownerText, userId = OWNER_TEXT, nil
if not ownerText then
	local ok, id = pcall(function()
		return game:GetService("StudioService"):GetUserId()
	end)
	if ok and id and id > 0 then
		userId = id
		local okName, name = pcall(function()
			return game:GetService("Players"):GetNameFromUserIdAsync(id)
		end)
		if okName then
			ownerText = name .. "'s Base"
		end
	end
end
nameLabel.Text = ownerText or "My Base"
if userId then
	avatar.Image = ("rbxthumb://type=AvatarHeadShot&id=%d&w=150&h=150"):format(userId)
end

-- earnings plaques and pet spots
for i = 1, 10 do
	local slot = find("Slots/Slot" .. i)
	slot:SetAttribute("SlotIndex", i)
	local top = slot.Top
	local spot = Instance.new("Attachment")
	spot.Name = "PetSpot"
	-- the cylinder lies on its side, so turn the attachment upright and facing the street (-Z)
	spot.CFrame = top.CFrame:ToObjectSpace(CFrame.new(top.Position + Vector3.new(0, top.Size.X / 2, 0)))
	spot.Parent = top
	local plaqueGui = Instance.new("SurfaceGui")
	plaqueGui.Name = "PlaqueGui"
	plaqueGui.Face = Enum.NormalId.Front
	plaqueGui.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
	plaqueGui.PixelsPerStud = 50
	plaqueGui.Parent = slot.Plaque
	label(plaqueGui, "EMPTY", Color3.fromHex("#FFFFFF"), Color3.fromHex("#0E1226"))
end

-- lamps glow onto the base
for _, d in ipairs(model:GetDescendants()) do
	if d:IsA("BasePart") and d.Name == "Lamp" then
		local light = Instance.new("PointLight")
		light.Color = d.Color
		light.Range = 14
		light.Brightness = 1.2
		light.Parent = d
	end
end

-- lock button label and door timer
local button = find("LockButton/Button")
local tag = Instance.new("BillboardGui")
tag.Name = "LockTag"
tag.Size = UDim2.fromScale(5, 1.4)
tag.StudsOffset = Vector3.new(0, 2.2, 0)
tag.AlwaysOnTop = false
tag.Parent = button
label(tag, "LOCK BASE", Color3.fromHex("#FFFFFF"), Color3.fromHex("#8A0F25"))

local field = find("Door/Field")
local timer = Instance.new("BillboardGui")
timer.Name = "LockTimer"
timer.Size = UDim2.fromScale(10, 2.2)
timer.StudsOffset = Vector3.new(0, 1, -1)
timer.Parent = field
label(timer, "LOCKED 0:30", Color3.fromHex("#7CFFB0"), Color3.fromHex("#0E1226"))

--[[ To lock or unlock from your game scripts:
local function setDoorLocked(base, locked)
	for _, p in ipairs(base.Door:GetChildren()) do
		p.Transparency = locked and 0 or 1
	end
	base.Door.Field.CanCollide = locked
	base.Door.Field.LockTimer.Enabled = locked
end
]]

model.PrimaryPart = find("Floor/Plinth")
model.WorldPivot = CFrame.new(0, 0, 0)
model:PivotTo(PLACE_AT)
model.Parent = workspace
print("BaseBuilder: built SlimeBase with " .. #PARTS .. " parts")
