--[[
	PropSetup (generated by slimes/tools/build_props.py; edit that, not this file)

	1. Import the prop .glb files with File > Import 3D. Keep the model names (ValleyGate, Tree_A, ...).
	2. Select the imported props (or select nothing to scan Workspace, ReplicatedStorage and
	   ServerStorage), paste this whole file into the Command Bar and press Enter.

	For each prop it:
	  - colours every part, sets its material and transparency, and turns collisions on only for the
	    solid parts (trunks, rocks, pillars), so players don't snag on petals and reeds
	  - anchors every part and moves them straight under the model
	  - puts the pivot at the bottom centre and scales the prop to its height in studs
	  - adds sign text (the gate's "SLIME VALLEY", the statue's plaque) and lights for glowing parts
	  - tags it with a PropZone attribute, which PropScatter.lua uses to find props for a zone

	Running it again is safe.
]]

local SPECS = {
	ValleyGate = { Zone = "Gate", Height = 30.3928, Main = "Arch", Signs = { { Part = "SignPanel", Text = "SLIME VALLEY", Color = Color3.fromRGB(255, 213, 74), PixelsPerStud = 20, FrontOnly = false } }, Lights = {  }, Parts = {
		Arch = { Color3.fromRGB(139, 234, 79), Enum.Material.SmoothPlastic, 0, true },
		Drips = { Color3.fromRGB(139, 234, 79), Enum.Material.SmoothPlastic, 0, false },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0, false },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0, false },
		Mouth = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0, false },
		SlimePink = { Color3.fromRGB(255, 123, 172), Enum.Material.SmoothPlastic, 0, true },
		SlimeBlue = { Color3.fromRGB(90, 176, 255), Enum.Material.SmoothPlastic, 0, true },
		SlimeYellow = { Color3.fromRGB(255, 213, 74), Enum.Material.SmoothPlastic, 0, true },
		SlimePurple = { Color3.fromRGB(142, 108, 255), Enum.Material.SmoothPlastic, 0, true },
		SlimeOrange = { Color3.fromRGB(255, 159, 67), Enum.Material.SmoothPlastic, 0, true },
		SlimeGreen = { Color3.fromRGB(110, 224, 122), Enum.Material.SmoothPlastic, 0, true },
		SignPanel = { Color3.fromRGB(30, 36, 64), Enum.Material.SmoothPlastic, 0, true },
		SignFrame = { Color3.fromRGB(255, 92, 122), Enum.Material.SmoothPlastic, 0, true },
		Straps = { Color3.fromRGB(139, 234, 79), Enum.Material.SmoothPlastic, 0, false },
	} },
	Meadow_FlowerClump = { Zone = "Meadow", Height = 3.8426, Main = "Stems", Signs = {  }, Lights = {  }, Parts = {
		Stems = { Color3.fromRGB(62, 155, 58), Enum.Material.SmoothPlastic, 0, false },
		Leaves = { Color3.fromRGB(88, 184, 74), Enum.Material.SmoothPlastic, 0, false },
		Grass = { Color3.fromRGB(76, 168, 67), Enum.Material.SmoothPlastic, 0, false },
		Centres = { Color3.fromRGB(255, 201, 61), Enum.Material.SmoothPlastic, 0, false },
		PetalsPink = { Color3.fromRGB(255, 143, 196), Enum.Material.SmoothPlastic, 0, false },
		PetalsWhite = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0, false },
		PetalsPurple = { Color3.fromRGB(180, 140, 255), Enum.Material.SmoothPlastic, 0, false },
		PetalsRed = { Color3.fromRGB(255, 90, 90), Enum.Material.SmoothPlastic, 0, false },
	} },
	Meadow_Mushrooms = { Zone = "Meadow", Height = 6.0273, Main = "Stems", Signs = {  }, Lights = {  }, Parts = {
		Stems = { Color3.fromRGB(243, 233, 210), Enum.Material.SmoothPlastic, 0, true },
		CapsRed = { Color3.fromRGB(226, 69, 60), Enum.Material.SmoothPlastic, 0, true },
		CapsOrange = { Color3.fromRGB(242, 140, 40), Enum.Material.SmoothPlastic, 0, false },
		Spots = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0, false },
		Grass = { Color3.fromRGB(76, 168, 67), Enum.Material.SmoothPlastic, 0, false },
	} },
	Meadow_Sunflower = { Zone = "Meadow", Height = 10.5937, Main = "Stem", Signs = {  }, Lights = {  }, Parts = {
		Stem = { Color3.fromRGB(62, 155, 58), Enum.Material.SmoothPlastic, 0, true },
		Leaves = { Color3.fromRGB(88, 184, 74), Enum.Material.SmoothPlastic, 0, false },
		Petals = { Color3.fromRGB(255, 210, 63), Enum.Material.SmoothPlastic, 0, false },
		Seeds = { Color3.fromRGB(107, 62, 31), Enum.Material.SmoothPlastic, 0, false },
	} },
	Swamp_DeadTree = { Zone = "Swamp", Height = 11.5018, Main = "Trunk", Signs = {  }, Lights = {  }, Parts = {
		Trunk = { Color3.fromRGB(107, 91, 78), Enum.Material.SmoothPlastic, 0, true },
		Branches = { Color3.fromRGB(107, 91, 78), Enum.Material.SmoothPlastic, 0, false },
		Moss = { Color3.fromRGB(126, 154, 85), Enum.Material.SmoothPlastic, 0, false },
	} },
	Swamp_Reeds = { Zone = "Swamp", Height = 5.0353, Main = "Stalks", Signs = {  }, Lights = {  }, Parts = {
		Stalks = { Color3.fromRGB(110, 143, 58), Enum.Material.SmoothPlastic, 0, false },
		Blades = { Color3.fromRGB(134, 168, 74), Enum.Material.SmoothPlastic, 0, false },
		Cattails = { Color3.fromRGB(122, 75, 42), Enum.Material.SmoothPlastic, 0, false },
	} },
	Lava_Spire = { Zone = "Lava", Height = 12.5024, Main = "Rock", Signs = {  }, Lights = {  }, Parts = {
		Rock = { Color3.fromRGB(58, 46, 43), Enum.Material.Slate, 0, true },
		Magma = { Color3.fromRGB(255, 106, 0), Enum.Material.Neon, 0, false },
		Rubble = { Color3.fromRGB(43, 34, 32), Enum.Material.Slate, 0, false },
	} },
	Lava_Vent = { Zone = "Lava", Height = 6.2400, Main = "Rock", Signs = {  }, Lights = {  }, Parts = {
		Rock = { Color3.fromRGB(58, 46, 43), Enum.Material.Slate, 0, true },
		Pool = { Color3.fromRGB(255, 122, 0), Enum.Material.Neon, 0, false },
		Embers = { Color3.fromRGB(255, 194, 61), Enum.Material.Neon, 0, false },
		Smoke = { Color3.fromRGB(154, 143, 140), Enum.Material.SmoothPlastic, 0.45, false },
	} },
	Crystal_Cluster = { Zone = "Crystal", Height = 8.6132, Main = "Crystals", Signs = {  }, Lights = {  }, Parts = {
		Crystals = { Color3.fromRGB(185, 167, 255), Enum.Material.Glass, 0.15, true },
		Cores = { Color3.fromRGB(231, 222, 255), Enum.Material.Neon, 0, false },
		Base = { Color3.fromRGB(94, 97, 120), Enum.Material.Slate, 0, true },
	} },
	Crystal_Shards = { Zone = "Crystal", Height = 4.3902, Main = "Crystals", Signs = {  }, Lights = {  }, Parts = {
		Crystals = { Color3.fromRGB(143, 233, 255), Enum.Material.Glass, 0.15, true },
		Cores = { Color3.fromRGB(224, 251, 255), Enum.Material.Neon, 0, false },
		Base = { Color3.fromRGB(94, 97, 120), Enum.Material.Slate, 0, true },
	} },
	Void_Obelisk = { Zone = "Void", Height = 11.8000, Main = "Obelisk", Signs = {  }, Lights = { "Capstone" }, Parts = {
		Obelisk = { Color3.fromRGB(26, 16, 36), Enum.Material.Slate, 0, true },
		Runes = { Color3.fromRGB(176, 38, 255), Enum.Material.Neon, 0, false },
		Capstone = { Color3.fromRGB(199, 125, 255), Enum.Material.Neon, 0, false },
		Steps = { Color3.fromRGB(18, 11, 26), Enum.Material.Slate, 0, true },
	} },
	Void_Shards = { Zone = "Void", Height = 6.5176, Main = "Shards", Signs = {  }, Lights = {  }, Parts = {
		Shards = { Color3.fromRGB(91, 33, 168), Enum.Material.Glass, 0.25, false },
		Cores = { Color3.fromRGB(199, 125, 255), Enum.Material.Neon, 0, false },
		GlowRing = { Color3.fromRGB(176, 38, 255), Enum.Material.Neon, 0, false },
		Rubble = { Color3.fromRGB(18, 11, 26), Enum.Material.Slate, 0, true },
	} },
	Tree_A = { Zone = "Street", Height = 20.6469, Main = "Trunk", Signs = {  }, Lights = {  }, Parts = {
		Trunk = { Color3.fromRGB(139, 90, 43), Enum.Material.Wood, 0, true },
		Leaves = { Color3.fromRGB(76, 191, 79), Enum.Material.SmoothPlastic, 0, true },
		LeavesDark = { Color3.fromRGB(56, 160, 64), Enum.Material.SmoothPlastic, 0, true },
	} },
	Tree_B = { Zone = "Street", Height = 23.8000, Main = "Trunk", Signs = {  }, Lights = {  }, Parts = {
		Trunk = { Color3.fromRGB(122, 74, 36), Enum.Material.Wood, 0, true },
		Needles = { Color3.fromRGB(46, 139, 87), Enum.Material.SmoothPlastic, 0, true },
		NeedlesLight = { Color3.fromRGB(63, 166, 106), Enum.Material.SmoothPlastic, 0, true },
	} },
	PlazaStatue = { Zone = "Plaza", Height = 11.9560, Main = "Plinth", Signs = { { Part = "Plaque", Text = "KING SLIME", Color = Color3.fromRGB(59, 42, 10), PixelsPerStud = 60, FrontOnly = true } }, Lights = {  }, Parts = {
		Plinth = { Color3.fromRGB(237, 231, 218), Enum.Material.Marble, 0, true },
		Trim = { Color3.fromRGB(212, 169, 58), Enum.Material.Metal, 0, true },
		Plaque = { Color3.fromRGB(201, 154, 46), Enum.Material.Metal, 0, false },
		Body = { Color3.fromRGB(227, 181, 59), Enum.Material.Metal, 0, true },
		Eyes = { Color3.fromRGB(90, 62, 18), Enum.Material.Metal, 0, false },
		EyeShine = { Color3.fromRGB(255, 241, 194), Enum.Material.Metal, 0, false },
		Mouth = { Color3.fromRGB(90, 62, 18), Enum.Material.Metal, 0, false },
		Cheeks = { Color3.fromRGB(227, 181, 59), Enum.Material.Metal, 0, false },
		Crown = { Color3.fromRGB(201, 146, 28), Enum.Material.Metal, 0, false },
		GemsRed = { Color3.fromRGB(224, 17, 95), Enum.Material.SmoothPlastic, 0, false },
		GemsBlue = { Color3.fromRGB(45, 108, 223), Enum.Material.SmoothPlastic, 0, false },
		GemsGreen = { Color3.fromRGB(31, 175, 90), Enum.Material.SmoothPlastic, 0, false },
		Cushion = { Color3.fromRGB(176, 16, 48), Enum.Material.SmoothPlastic, 0, false },
	} },
}

local function partKey(parts, name)
	if parts[name] then
		return name
	end
	for key in pairs(parts) do
		if name:sub(1, #key) == key and not name:sub(#key + 1, #key + 1):match("%w") then
			return key
		end
	end
	return nil
end

local function isProp(model, spec)
	local any = false
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("BasePart") then
			if not partKey(spec.Parts, d.Name) then
				return false
			end
			any = true
		end
	end
	return any
end

local function addSign(part, sign)
	for _, c in ipairs(part:GetChildren()) do
		if c:IsA("SurfaceGui") and c.Name:match("^SignGui") then
			c:Destroy()
		end
	end
	local faces = sign.FrontOnly and { Enum.NormalId.Front } or { Enum.NormalId.Front, Enum.NormalId.Back }
	for _, face in ipairs(faces) do
		local gui = Instance.new("SurfaceGui")
		gui.Name = "SignGui" .. face.Name
		gui.Face = face
		gui.SizingMode = Enum.SurfaceGuiSizingMode.PixelsPerStud
		gui.PixelsPerStud = sign.PixelsPerStud
		gui.LightInfluence = 0
		local label = Instance.new("TextLabel")
		label.Name = "Label"
		label.BackgroundTransparency = 1
		label.AnchorPoint = Vector2.new(0.5, 0.5)
		label.Position = UDim2.fromScale(0.5, 0.5)
		label.Size = UDim2.fromScale(0.92, 0.8)
		label.Font = Enum.Font.FredokaOne
		label.TextScaled = true
		label.Text = sign.Text
		label.TextColor3 = sign.Color
		local stroke = Instance.new("UIStroke")
		stroke.Color = Color3.new(0, 0, 0)
		stroke.Transparency = 0.4
		stroke.Thickness = 3
		stroke.Parent = label
		label.Parent = gui
		gui.Parent = part
	end
end

local function setup(model, spec)
	local parts = {}
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("BasePart") then
			table.insert(parts, d)
		end
	end
	for _, p in ipairs(parts) do
		p.Parent = model
	end
	for _, c in ipairs(model:GetChildren()) do
		if (c:IsA("Model") or c:IsA("Folder")) and #c:GetDescendants() == 0 then
			c:Destroy()
		end
	end

	local main
	for _, p in ipairs(parts) do
		local key = partKey(spec.Parts, p.Name)
		local look = spec.Parts[key]
		p.Name = key
		p.Color, p.Material, p.Transparency = look[1], look[2], look[3]
		p.Anchored = true
		p.CanCollide = look[4]
		p.CanTouch = look[4]
		p.CanQuery = look[4]
		p.CastShadow = look[2] ~= Enum.Material.Neon and look[3] < 0.3
		for _, c in ipairs(p:GetChildren()) do
			if c:IsA("SurfaceAppearance") or (c:IsA("PointLight") and c.Name == "PropLight") then
				c:Destroy()
			end
		end
		if key == spec.Main and not main then
			main = p
		end
	end
	model.PrimaryPart = main

	local cf, size = model:GetBoundingBox()
	local bottom = cf.Position - Vector3.new(0, size.Y / 2, 0)
	model.WorldPivot = CFrame.new(bottom)
	if size.Y > 0 then
		local factor = spec.Height / size.Y
		if math.abs(factor - 1) > 1e-3 then
			model:ScaleTo(model:GetScale() * factor)
		end
	end

	for _, sign in ipairs(spec.Signs) do
		for _, p in ipairs(parts) do
			if p.Name == sign.Part then
				addSign(p, sign)
			end
		end
	end
	for _, name in ipairs(spec.Lights) do
		for _, p in ipairs(parts) do
			if p.Name == name then
				local light = Instance.new("PointLight")
				light.Name = "PropLight"
				light.Color = p.Color
				light.Range = 16
				light.Brightness = 1.5
				light.Parent = p
			end
		end
	end
	model:SetAttribute("PropZone", spec.Zone)
end

local candidates = {}
local okSel, selection = pcall(function()
	return game:GetService("Selection"):Get()
end)
if okSel and #selection > 0 then
	for _, s in ipairs(selection) do
		table.insert(candidates, s)
		for _, d in ipairs(s:GetDescendants()) do
			table.insert(candidates, d)
		end
	end
else
	for _, service in ipairs({ workspace, game:GetService("ReplicatedStorage"), game:GetService("ServerStorage") }) do
		for _, d in ipairs(service:GetDescendants()) do
			table.insert(candidates, d)
		end
	end
end

local done = {}
for _, m in ipairs(candidates) do
	local spec = m:IsA("Model") and SPECS[m.Name]
	if spec and m.Parent and isProp(m, spec) then
		setup(m, spec)
		table.insert(done, m.Name)
	end
end
print(("PropSetup: set up %d prop(s): %s"):format(#done, table.concat(done, ", ")))
