--[[
	SlimeSetup (generated by slimes/tools/build_slimes.py; edit that, not this file)

	1. Import the .glb files with File > Import 3D. Keep the model names (LilGreen, BlueBlob, ...).
	2. Select the imported slimes (or select nothing to scan Workspace, ReplicatedStorage and
	   ServerStorage), paste this whole file into the Command Bar and press Enter.

	For each slime model it:
	  - colours every part and sets its material and transparency
	  - moves the parts straight under the model and welds them to Body (the PrimaryPart)
	  - puts the pivot at the bottom centre, turned so the pivot's LookVector is the way the face looks
	  - scales the model to its size in studs
	  - adds Rarity and Size attributes

	Running it again is safe. A model is only touched when every part in it is a known slime part,
	so other models that happen to be called King or Ghost are left alone.
]]

local SPECS = {
	LilGreen = { Rarity = "Common", Size = 3, BodyWidth = 2.9984, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(105, 210, 75), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
	} },
	BlueBlob = { Rarity = "Common", Size = 3, BodyWidth = 2.9984, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(79, 163, 247), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		Eyelids = { Color3.fromRGB(79, 163, 247), Enum.Material.SmoothPlastic, 0 },
		Lashes = { Color3.fromRGB(22, 50, 92), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(22, 50, 92), Enum.Material.SmoothPlastic, 0 },
		Zzz = { Color3.fromRGB(234, 245, 255), Enum.Material.SmoothPlastic, 0 },
	} },
	Pinky = { Rarity = "Common", Size = 3, BodyWidth = 2.9984, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(255, 156, 200), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Cheeks = { Color3.fromRGB(255, 94, 153), Enum.Material.SmoothPlastic, 0 },
		BlushLines = { Color3.fromRGB(224, 64, 122), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
	} },
	Mudsy = { Rarity = "Common", Size = 3, BodyWidth = 2.9984, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(123, 81, 52), Enum.Material.SmoothPlastic, 0 },
		Puddle = { Color3.fromRGB(94, 59, 36), Enum.Material.SmoothPlastic, 0 },
		Drips = { Color3.fromRGB(123, 81, 52), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Pupils = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(59, 30, 16), Enum.Material.SmoothPlastic, 0 },
		Tongue = { Color3.fromRGB(255, 127, 154), Enum.Material.SmoothPlastic, 0 },
		Tooth = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
	} },
	Bubblegum = { Rarity = "Uncommon", Size = 3.2, BodyWidth = 3.1983, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(255, 63, 164), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Cheeks = { Color3.fromRGB(255, 119, 190), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(176, 24, 106), Enum.Material.SmoothPlastic, 0 },
		Bubble = { Color3.fromRGB(255, 140, 203), Enum.Material.SmoothPlastic, 0.3 },
		BubbleShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0.1 },
	} },
	LemonDrop = { Rarity = "Uncommon", Size = 3.2, BodyWidth = 3.1983, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(255, 232, 115), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		Cheeks = { Color3.fromRGB(255, 179, 107), Enum.Material.SmoothPlastic, 0 },
		LemonRind = { Color3.fromRGB(242, 196, 0), Enum.Material.SmoothPlastic, 0 },
		LemonFlesh = { Color3.fromRGB(255, 242, 122), Enum.Material.SmoothPlastic, 0 },
		LemonPith = { Color3.fromRGB(255, 252, 230), Enum.Material.SmoothPlastic, 0 },
	} },
	Minty = { Rarity = "Uncommon", Size = 3.2, BodyWidth = 3.1983, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(143, 240, 200), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		Cheeks = { Color3.fromRGB(255, 158, 181), Enum.Material.SmoothPlastic, 0 },
		Leaf = { Color3.fromRGB(47, 168, 79), Enum.Material.SmoothPlastic, 0 },
		LeafVein = { Color3.fromRGB(30, 122, 56), Enum.Material.SmoothPlastic, 0 },
		Stem = { Color3.fromRGB(107, 74, 43), Enum.Material.SmoothPlastic, 0 },
	} },
	TopHat = { Rarity = "Rare", Size = 3.6, BodyWidth = 3.5980, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(242, 166, 90), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Hat = { Color3.fromRGB(30, 30, 38), Enum.Material.SmoothPlastic, 0 },
		HatBand = { Color3.fromRGB(183, 28, 44), Enum.Material.SmoothPlastic, 0 },
		Monocle = { Color3.fromRGB(232, 184, 48), Enum.Material.Metal, 0 },
		Lens = { Color3.fromRGB(216, 243, 255), Enum.Material.Glass, 0.55 },
		Mustache = { Color3.fromRGB(59, 38, 24), Enum.Material.SmoothPlastic, 0 },
	} },
	Ninja = { Rarity = "Rare", Size = 3.6, BodyWidth = 3.5980, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(35, 35, 43), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Pupils = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		Brows = { Color3.fromRGB(35, 35, 43), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(90, 90, 102), Enum.Material.SmoothPlastic, 0 },
		Headband = { Color3.fromRGB(215, 38, 61), Enum.Material.SmoothPlastic, 0 },
	} },
	Lava = { Rarity = "Rare", Size = 3.6, BodyWidth = 3.6343, Face = "Eyes", Parts = {
		Core = { Color3.fromRGB(255, 90, 0), Enum.Material.Neon, 0 },
		Body = { Color3.fromRGB(58, 43, 39), Enum.Material.Slate, 0 },
		Eyes = { Color3.fromRGB(255, 210, 63), Enum.Material.Neon, 0 },
		Mouth = { Color3.fromRGB(255, 140, 26), Enum.Material.Neon, 0 },
	} },
	Frost = { Rarity = "Epic", Size = 4, BodyWidth = 3.9978, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(143, 216, 255), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(26, 46, 74), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(26, 46, 74), Enum.Material.SmoothPlastic, 0 },
		Cheeks = { Color3.fromRGB(255, 184, 217), Enum.Material.SmoothPlastic, 0 },
		Snow = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Crystals = { Color3.fromRGB(221, 247, 255), Enum.Material.Glass, 0.2 },
	} },
	Royal = { Rarity = "Epic", Size = 4, BodyWidth = 3.9978, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(138, 79, 216), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		Crown = { Color3.fromRGB(242, 194, 48), Enum.Material.Metal, 0 },
		Gems = { Color3.fromRGB(224, 17, 95), Enum.Material.SmoothPlastic, 0 },
		Cape = { Color3.fromRGB(193, 18, 31), Enum.Material.SmoothPlastic, 0 },
		Collar = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
	} },
	Ghost = { Rarity = "Epic", Size = 4, BodyWidth = 3.9221, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(242, 245, 255), Enum.Material.SmoothPlastic, 0.3 },
		Arms = { Color3.fromRGB(242, 245, 255), Enum.Material.SmoothPlastic, 0.3 },
		Eyes = { Color3.fromRGB(43, 45, 66), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(43, 45, 66), Enum.Material.SmoothPlastic, 0 },
		Cheeks = { Color3.fromRGB(201, 211, 255), Enum.Material.SmoothPlastic, 0 },
	} },
	Devil = { Rarity = "Legendary", Size = 4.5, BodyWidth = 4.4976, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(217, 38, 58), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Brows = { Color3.fromRGB(94, 10, 22), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(58, 10, 16), Enum.Material.SmoothPlastic, 0 },
		Fang = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Horns = { Color3.fromRGB(42, 11, 16), Enum.Material.SmoothPlastic, 0 },
		Tail = { Color3.fromRGB(194, 31, 51), Enum.Material.SmoothPlastic, 0 },
		TailTip = { Color3.fromRGB(42, 11, 16), Enum.Material.SmoothPlastic, 0 },
	} },
	Angel = { Rarity = "Legendary", Size = 4.5, BodyWidth = 4.4976, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(255, 240, 212), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(58, 42, 26), Enum.Material.SmoothPlastic, 0 },
		Cheeks = { Color3.fromRGB(255, 179, 179), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(58, 42, 26), Enum.Material.SmoothPlastic, 0 },
		Halo = { Color3.fromRGB(255, 216, 74), Enum.Material.Neon, 0 },
		Wings = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
	} },
	Galaxy = { Rarity = "Legendary", Size = 4.5, BodyWidth = 4.4976, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(44, 26, 92), Enum.Material.SmoothPlastic, 0.22 },
		Nebula = { Color3.fromRGB(155, 63, 224), Enum.Material.SmoothPlastic, 0.55 },
		Stars = { Color3.fromRGB(255, 244, 184), Enum.Material.Neon, 0 },
		Sparkles = { Color3.fromRGB(159, 232, 255), Enum.Material.Neon, 0 },
		Eyes = { Color3.fromRGB(255, 255, 255), Enum.Material.Neon, 0 },
		Mouth = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
	} },
	Dragon = { Rarity = "Mythic", Size = 5.2, BodyWidth = 5.1972, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(63, 163, 77), Enum.Material.SmoothPlastic, 0 },
		Belly = { Color3.fromRGB(243, 220, 138), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Nostrils = { Color3.fromRGB(31, 92, 41), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(31, 63, 34), Enum.Material.SmoothPlastic, 0 },
		Fangs = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Horns = { Color3.fromRGB(232, 181, 48), Enum.Material.SmoothPlastic, 0 },
		Spikes = { Color3.fromRGB(232, 181, 48), Enum.Material.SmoothPlastic, 0 },
		Wings = { Color3.fromRGB(47, 138, 62), Enum.Material.SmoothPlastic, 0 },
		WingBones = { Color3.fromRGB(232, 181, 48), Enum.Material.SmoothPlastic, 0 },
	} },
	Void = { Rarity = "Mythic", Size = 5.2, BodyWidth = 5.1972, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(5, 5, 8), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(176, 38, 255), Enum.Material.Neon, 0 },
		Orbs = { Color3.fromRGB(122, 31, 209), Enum.Material.Neon, 0 },
	} },
	King = { Rarity = "Secret", Size = 6.5, BodyWidth = 6.4965, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(247, 197, 49), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		Cheeks = { Color3.fromRGB(255, 154, 90), Enum.Material.SmoothPlastic, 0 },
		Crown = { Color3.fromRGB(224, 164, 14), Enum.Material.Metal, 0 },
		GemsRed = { Color3.fromRGB(224, 17, 95), Enum.Material.SmoothPlastic, 0 },
		GemsBlue = { Color3.fromRGB(45, 108, 223), Enum.Material.SmoothPlastic, 0 },
		GemsGreen = { Color3.fromRGB(31, 175, 90), Enum.Material.SmoothPlastic, 0 },
		Cushion = { Color3.fromRGB(176, 16, 48), Enum.Material.SmoothPlastic, 0 },
	} },
	Glitch = { Rarity = "Secret", Size = 6.5, BodyWidth = 6.5000, Face = "Face", Parts = {
		Body = { Color3.fromRGB(57, 255, 20), Enum.Material.SmoothPlastic, 0 },
		Chunks = { Color3.fromRGB(255, 31, 224), Enum.Material.Neon, 0 },
		Face = { Color3.fromRGB(11, 11, 11), Enum.Material.SmoothPlastic, 0 },
		Bits = { Color3.fromRGB(255, 31, 224), Enum.Material.Neon, 0 },
		BitsGreen = { Color3.fromRGB(57, 255, 20), Enum.Material.Neon, 0 },
	} },
	Gummy = { Rarity = "Legendary", Size = 4.5, BodyWidth = 4.4976, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(255, 59, 92), Enum.Material.SmoothPlastic, 0.25 },
		Core = { Color3.fromRGB(255, 122, 144), Enum.Material.SmoothPlastic, 0 },
		Ears = { Color3.fromRGB(255, 59, 92), Enum.Material.SmoothPlastic, 0.25 },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		Cheeks = { Color3.fromRGB(255, 179, 193), Enum.Material.SmoothPlastic, 0 },
		Sugar = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
	} },
	CottonCandy = { Rarity = "Mythic", Size = 5.2, BodyWidth = 5.1972, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(255, 194, 226), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(27, 27, 31), Enum.Material.SmoothPlastic, 0 },
		Cheeks = { Color3.fromRGB(255, 140, 198), Enum.Material.SmoothPlastic, 0 },
		Fluff = { Color3.fromRGB(255, 176, 218), Enum.Material.SmoothPlastic, 0 },
		FluffBlue = { Color3.fromRGB(168, 221, 255), Enum.Material.SmoothPlastic, 0 },
		FluffWhite = { Color3.fromRGB(255, 242, 250), Enum.Material.SmoothPlastic, 0 },
		Stick = { Color3.fromRGB(247, 231, 198), Enum.Material.SmoothPlastic, 0 },
		Sprinkles = { Color3.fromRGB(124, 227, 255), Enum.Material.SmoothPlastic, 0 },
		SprinklesYellow = { Color3.fromRGB(255, 224, 102), Enum.Material.SmoothPlastic, 0 },
	} },
	Thunder = { Rarity = "Secret", Size = 6.5, BodyWidth = 6.4965, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(91, 107, 140), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(255, 225, 77), Enum.Material.Neon, 0 },
		Mouth = { Color3.fromRGB(42, 51, 80), Enum.Material.SmoothPlastic, 0 },
		Cloud = { Color3.fromRGB(213, 221, 234), Enum.Material.SmoothPlastic, 0 },
		CloudDark = { Color3.fromRGB(154, 166, 188), Enum.Material.SmoothPlastic, 0 },
		Bolts = { Color3.fromRGB(255, 225, 77), Enum.Material.Neon, 0 },
		Sparks = { Color3.fromRGB(159, 232, 255), Enum.Material.Neon, 0 },
	} },
	Phoenix = { Rarity = "Secret", Size = 6.5, BodyWidth = 6.4965, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(255, 106, 43), Enum.Material.SmoothPlastic, 0 },
		Belly = { Color3.fromRGB(255, 200, 87), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(58, 18, 0), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Beak = { Color3.fromRGB(255, 210, 63), Enum.Material.SmoothPlastic, 0 },
		Flames = { Color3.fromRGB(255, 138, 0), Enum.Material.Neon, 0 },
		FlamesInner = { Color3.fromRGB(255, 225, 77), Enum.Material.Neon, 0 },
		Wings = { Color3.fromRGB(255, 74, 28), Enum.Material.SmoothPlastic, 0 },
		WingTips = { Color3.fromRGB(255, 210, 63), Enum.Material.SmoothPlastic, 0 },
		Tail = { Color3.fromRGB(255, 138, 0), Enum.Material.Neon, 0 },
	} },
	Supernova = { Rarity = "Divine", Size = 7, BodyWidth = 6.9962, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(255, 233, 168), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(74, 42, 0), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(74, 42, 0), Enum.Material.SmoothPlastic, 0 },
		Cheeks = { Color3.fromRGB(255, 158, 107), Enum.Material.SmoothPlastic, 0 },
		Corona = { Color3.fromRGB(255, 176, 32), Enum.Material.Neon, 0 },
		RingPink = { Color3.fromRGB(255, 92, 200), Enum.Material.Neon, 0 },
		Rays = { Color3.fromRGB(255, 244, 194), Enum.Material.Neon, 0 },
		Stars = { Color3.fromRGB(255, 255, 255), Enum.Material.Neon, 0 },
	} },
	BlackHole = { Rarity = "Divine", Size = 7, BodyWidth = 6.9962, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(5, 5, 7), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(233, 210, 255), Enum.Material.Neon, 0 },
		Mouth = { Color3.fromRGB(176, 38, 255), Enum.Material.Neon, 0 },
		DiskInner = { Color3.fromRGB(255, 138, 61), Enum.Material.Neon, 0 },
		DiskOuter = { Color3.fromRGB(155, 48, 255), Enum.Material.Neon, 0.25 },
		PhotonRing = { Color3.fromRGB(255, 231, 194), Enum.Material.Neon, 0 },
		Debris = { Color3.fromRGB(199, 125, 255), Enum.Material.Neon, 0 },
	} },
	Omega = { Rarity = "Divine", Size = 7, BodyWidth = 6.9962, Face = "Eyes", Parts = {
		Body = { Color3.fromRGB(244, 240, 255), Enum.Material.SmoothPlastic, 0 },
		Eyes = { Color3.fromRGB(42, 31, 74), Enum.Material.SmoothPlastic, 0 },
		EyeShine = { Color3.fromRGB(255, 255, 255), Enum.Material.SmoothPlastic, 0 },
		Mouth = { Color3.fromRGB(42, 31, 74), Enum.Material.SmoothPlastic, 0 },
		Cheeks = { Color3.fromRGB(201, 184, 255), Enum.Material.SmoothPlastic, 0 },
		Emblem = { Color3.fromRGB(255, 213, 74), Enum.Material.Neon, 0 },
		Halo = { Color3.fromRGB(255, 213, 74), Enum.Material.Neon, 0 },
		WingsCyan = { Color3.fromRGB(143, 243, 255), Enum.Material.Glass, 0.2 },
		WingsPink = { Color3.fromRGB(255, 158, 234), Enum.Material.Glass, 0.2 },
		OrbitRing = { Color3.fromRGB(185, 167, 255), Enum.Material.Neon, 0 },
	} },
}

local function partKey(parts, name)
	if parts[name] then
		return name
	end
	-- the importer can add a suffix such as "Body_1"
	for key in pairs(parts) do
		if name:sub(1, #key) == key and not name:sub(#key + 1, #key + 1):match("%w") then
			return key
		end
	end
	return nil
end

local function worldBounds(part)
	local cf, half = part.CFrame, part.Size / 2
	local lo = Vector3.new(math.huge, math.huge, math.huge)
	local hi = -lo
	for _, x in ipairs({ -1, 1 }) do
		for _, y in ipairs({ -1, 1 }) do
			for _, z in ipairs({ -1, 1 }) do
				local p = cf:PointToWorldSpace(Vector3.new(x * half.X, y * half.Y, z * half.Z))
				lo = lo:Min(p)
				hi = hi:Max(p)
			end
		end
	end
	return lo, hi
end

local function isSlime(model, spec)
	local hasBody = false
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("BasePart") then
			local key = partKey(spec.Parts, d.Name)
			if not key then
				return false
			end
			hasBody = hasBody or key == "Body"
		end
	end
	return hasBody
end

local function setup(model, spec)
	local parts = {}
	for _, d in ipairs(model:GetDescendants()) do
		if d:IsA("BasePart") then
			table.insert(parts, d)
		end
	end

	-- flatten whatever nesting the importer made
	for _, p in ipairs(parts) do
		p.Parent = model
	end
	for _, c in ipairs(model:GetChildren()) do
		if (c:IsA("Model") or c:IsA("Folder")) and #c:GetDescendants() == 0 then
			c:Destroy()
		end
	end

	local body
	local facePos, faceCount = Vector3.zero, 0
	for _, p in ipairs(parts) do
		local key = partKey(spec.Parts, p.Name)
		local look = spec.Parts[key]
		p.Name = key
		p.Color, p.Material, p.Transparency = look[1], look[2], look[3]
		for _, c in ipairs(p:GetChildren()) do
			if c:IsA("SurfaceAppearance") or (c:IsA("WeldConstraint") and c.Name == "SlimeWeld") then
				c:Destroy()
			end
		end
		if key == "Body" and not body then
			body = p
		end
		if key == spec.Face then
			facePos += p.Position
			faceCount += 1
		end
	end

	model.PrimaryPart = body
	for _, p in ipairs(parts) do
		if p == body then
			p.Anchored = true
		else
			p.Anchored = false
			p.CanCollide = false
			p.CanTouch = false
			p.CanQuery = false
			p.Massless = true
			local weld = Instance.new("WeldConstraint")
			weld.Name = "SlimeWeld"
			weld.Part0 = body
			weld.Part1 = p
			weld.Parent = p
		end
	end

	-- pivot at the bottom centre of the body, looking the way the face looks
	local lo, hi = worldBounds(body)
	local centre = (lo + hi) / 2
	local bottom = Vector3.new(centre.X, lo.Y, centre.Z)
	local look = Vector3.new(0, 0, -1)
	if faceCount > 0 then
		local f = facePos / faceCount - centre
		if Vector3.new(f.X, 0, f.Z).Magnitude > 1e-3 then
			look = Vector3.new(f.X, 0, f.Z).Unit
		end
	end
	model.WorldPivot = CFrame.lookAt(bottom, bottom + look)
	model:PivotTo(CFrame.new(bottom))

	-- exact size: the body is BodyWidth studs across
	local lo2, hi2 = worldBounds(body)
	local width = hi2.X - lo2.X
	if width > 0 then
		local factor = spec.BodyWidth / width
		if math.abs(factor - 1) > 1e-3 then
			model:ScaleTo(model:GetScale() * factor)
		end
	end

	model:SetAttribute("Rarity", spec.Rarity)
	model:SetAttribute("Size", spec.Size)
	return true
end

local candidates = {}
local okSel, selection = pcall(function()
	return game:GetService("Selection"):Get()
end)
if okSel and #selection > 0 then
	for _, s in ipairs(selection) do
		table.insert(candidates, s)
		for _, d in ipairs(s:GetDescendants()) do
			table.insert(candidates, d)
		end
	end
else
	for _, service in ipairs({ workspace, game:GetService("ReplicatedStorage"), game:GetService("ServerStorage") }) do
		for _, d in ipairs(service:GetDescendants()) do
			table.insert(candidates, d)
		end
	end
end

local done = {}
for _, m in ipairs(candidates) do
	local spec = m:IsA("Model") and SPECS[m.Name]
	if spec and m.Parent and isSlime(m, spec) then
		setup(m, spec)
		table.insert(done, m.Name)
	end
end
print(("SlimeSetup: set up %d slime(s): %s"):format(#done, table.concat(done, ", ")))
